name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5
      - run: yarn report:merge
      - run: yarn report:mocha

      - name: Reports deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: mochawesome-report
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Copy videos
        uses: andstor/copycat-action@v3
        with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
            src_path: cypress/videos/*
            dst_path: /.
            dst_owner: FluffyBubu
            dst_repo_name: cypress-gh-pages-reporting
            dst_branch: gh-pages
