name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-split-results
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
          if-no-files-found: ignore

  merge-reports:
    needs: cypress-run
    if: always()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Install dependencies 🧪
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      # https://github.com/actions/download-artifact
      - uses: actions/download-artifact@v3
        with:
          path: split-results
      - name: Display structure of downloaded files
        run: ls -R split-results

      - name: Prepare folder
        run: |
          mkdir mochawesome
          mkdir -p mochawesome-report/cypress/videos
          mkdir -p mochawesome-report/cypress/screenshots
          mkdir -p mochawesome-report/cypress/results
      - name: Copy all assets and JSON reports
        run: |
          cp -r split-results/cypress-split-results/videos/* mochawesome-report/cypress/videos || true
          cp -r split-results/cypress-split-results/screenshots/* mochawesome-report/cypress/screenshots || true
          cp -r split-results/cypress-split-results/results/* mochawesome-report/cypress/results || true
      - name: Show copied files
        run: ls -lR mochawesome-report

      - name: Merge Mochawesome JSON reports
        run: yarn report:merge
      - name: Generate Mochawesome HTML report
        run: yarn report:mocha

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: mochawesome-report
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          clean: true

      - uses: actions/upload-artifact@v3
        with:
          name: merged-mochawesome-report
          path: mochawesome-report
