name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5
      - uses: actions/upload-artifact@v3
        with:
            name: cypress-screenshots
            path: cypress/screenshots
            if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        with:
            name: cypress-videos
            path: cypress/videos
            if-no-files-found: ignore
      - run: yarn report:merge
      - run: yarn report:mocha


      - name: Reports deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: mochawesome-report
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
          
      - name: Download cypress-videos artifact
        uses: actions/download-artifact@v3
        with:
            name: cypress-videos
            path: ./cypress/videos/
        
      - name: Copy videos to gh-pages 🎬
        uses: andstor/copycat-action@v3
        with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
            src_path: ./cypress/videos/**
            dst_path: ./
            dst_owner: FluffyBubu
            dst_repo_name: cypress-gh-pages-reporting
            dst_branch: gh-pages
            clean: true