name: End-to-end tests
on: push
jobs:
  # example splitting all tests across GitHub machines
  prepare:
    runs-on: ubuntu-22.04
    # explicitly set the output of this job
    # so that other jobs can use it
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: 2 # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  test-split:
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Print GitHub variables 🖨
        run: npx @bahmutov/print-env GITHUB

      - name: Print GitHub strategy context 🖨
        run: echo '${{ toJSON(strategy) }}'

      - name: Run split Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: cypress-split
      - uses: actions/upload-artifact@v3
        with:
              name: cypress-screenshots
              path: cypress/screenshots
              if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        with:
              name: cypress-videos
              path: cypress/videos
              if-no-files-found: ignore
      - run: yarn report:merge
      - run: yarn report:mocha

      - name: Reports deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: gh-pages
            folder: mochawesome-report
            ssh-key: ${{ secrets.DEPLOY_KEY }}